# UI Settings
WINDOW_TITLE = "Auto Drawing V1.0"
WINDOW_SIZE = "1200x700"
WINDOW_BG = '#f0f0f0'

# Drawing Settings
DEFAULT_SPEED = 0.001
DEFAULT_POINT_DENSITY = 0.5
DEFAULT_EDGE_THICKNESS = 2
DEFAULT_NUM_COLORS = 8
FAST_MODE_BATCH_SIZE = 10
NORMAL_MODE_BATCH_SIZE = 3

# Colors
COLOR_PRIMARY = '#4CAF50'
COLOR_SECONDARY = '#2196F3'
COLOR_WARNING = '#FF9800'
COLOR_DANGER = '#F44336'
COLOR_INFO = '#00ff88'

# Hotkeys
HOTKEY_PAUSE_RESUME = 'f5'
HOTKEY_STOP = 'f6'
HOTKEY_TOGGLE_OVERLAY = 'f7'

# PyAutoGUI Settings
PYAUTOGUI_FAILSAFE = True
PYAUTOGUI_PAUSE = 0

# Image Processing
THUMBNAIL_SIZE = (600, 600)
COLOR_ANALYSIS_SIZE = (100, 100)

# Progress Update
COUNTDOWN_UPDATE_INTERVAL = 1
PROGRESS_UPDATE_FREQUENCY = 50
